on:
  push:
    branches:
    - main
    - feature/*
    - release/*
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

name: Build and Test Module

jobs:
### RUN CHECKS ###
  run_checks:
    uses: alztestappvia/alz_cicd_templates/.github/workflows/terraform-checks.yaml@main
    name: Run Checks
    with:
      terraform-working-directory: .
    secrets:
      GH_TOKEN: ${{ secrets.ALZ_GITHUB_MODULE_READ_TOKEN }}
  